name: Sync repos
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository == 'scalr-automation/terraform-scalr-flat'
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Set up Git
        run: |
          git config --global user.name "scalr-autotester"
          git config --global user.email "scalr-autotester@scalr.com"
          git config --unset-all http.https://github.com/.extraheader
      - name: Sync repositories
        run: |
          git remote add repo1 https://scalr-autotester13:${{ secrets.GH_PAT_13_2 }}@github.com/scalr-automation/terraform-scalr-flat-mirror1.git
          git push --force repo1 main --follow-tags
